modLoader="javafml"
loaderVersion="[35,]"
issueTrackerURL="http://github.com/coolsimulations/morethanapickaxe/issues/"
logoFile="logo.png"
license="All rights reserved"

[[mods]]
    modId="morethanapickaxe"
    version="0.1.4"
    updateJSONURL="https://coolsimulations.net/mcmods/morethanapickaxe/versionchecker.json"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/more-than-a-pickaxe"
    displayName="More Than A Pickaxe"
    credits="Inspired by a couple of other mods such as Paxel and Multitools."
    authors="coolsim"
    description='''
    This mod is an add-on to SurvivalPlus that adds a multitool which is a pickaxe, axe, sword, hoe, and shovel.
    '''
[[dependencies.morethanapickaxe]]
    modId="forge"
    mandatory=true
    versionRange="[35.0.15,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.morethanapickaxe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.morethanapickaxe]]
    modId="survivalplus"
    mandatory=true
    versionRange="[0.1.4c,)"
    ordering="BEFORE"
    side="BOTH"